inherit_from: .rubocop_todo.yml

Style/NumericPredicate:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Naming/MethodName:
  Exclude:
    - 'spec/code_object_spec.rb'
    - 'lib/pry/method.rb'
    - 'lib/pry/wrapped_module.rb'
    - 'lib/pry/code.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/pry/config/behavior.rb'

Layout/CommentIndentation:
  Exclude:
    - 'spec/fixtures/example_nesting.rb'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/fixtures/example_nesting.rb'

# TODO: delete exclusions when we drop Ruby 1.9.3 support.
Style/ExpandPathArguments:
  Exclude:
    - 'lib/pry/commands.rb'
    - 'pry.gemspec'

Style/Semicolon:
  Exclude:
    - 'spec/method_spec.rb'

Style/SingleLineMethods:
  Exclude:
    - 'spec/method_spec.rb'
    - 'spec/fixtures/example_nesting.rb'

Style/StringLiterals:
  Enabled: false

# TODO: delete this rule when we drop Ruby 1.9.3 support.
Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/LineLength:
  Max: 90

Bundler/OrderedGems:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/CommentedKeyword:
  Exclude:
    - 'spec/fixtures/example_nesting.rb'

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  Exclude:
    - 'spec/fixtures/example_nesting.rb'
